name: most_colours
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  web: ^0.4.0
  image: ^4.1.7
  archive: ^3.4.10
  color: ^3.0.0
  yaml: ^3.1.2
  yaml_writer: ^2.0.0
  sorted: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
